apiVersion: v1
kind: Namespace
metadata:
  name: big-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: big-data
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Cassandra
        type: hadesarchitect-cassandra-datasource
        access: proxy
        url: cassandra:9042
        jsonData:
          keyspace: taxi_streaming
          consistency: ONE
        isDefault: true
        editable: true
