apiVersion: v1
kind: Namespace
metadata:
  name: mta-project
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mta-config
  namespace: mta-project
# Trong 00-core.yaml
data:
  KAFKA_BOOTSTRAP_SERVERS: "broker-service:9092"
  KAFKA_BROKER: "broker-service:9092"
  CASSANDRA_HOST: "cassandra-service" # Theo image_b934fc.png
  HDFS_NAMENODE: "hdfs://namenode-service:8020" # Theo image_b934fc.png